export const products = [
  {
    id: 1,
    name: 'ونس قهوه ای',
    description: [
      { support: 'گارانتی مادام العمر' },
      { support: 'ارسال رایگان' },
      { support: 'اورجینال' },
    ],
    price: 120000,
    offPrice: 120000,
    discount: 0,
    image: 'https://s4.uupload.ir/files/item1_soj.jpg',
  },
  {
    id: 2,
    name: 'آدیداس',
    description: [{ support: 'گارانتی مادام العمر' }, { support: 'اورجینال' }],
    price: 110000,
    offPrice: 100000,
    discount: 8,
    image: 'https://s4.uupload.ir/files/item2_fc5s.jpg',
  },
  {
    id: 3,
    name: 'ونس',
    description: [
      { support: 'گارانتی مادام العمر' },
      { support: 'اورجینال' },
      { support: 'ارسال رایگان' },
    ],
    price: 990000,
    offPrice: 890000,
    discount: 10,
    image: 'https://s4.uupload.ir/files/item3_zvc9.jpg',
  },
  {
    id: 4,
    name: 'کتونی سفید',
    description: [
      { support: 'گارانتی مادام العمر' },
      { support: 'اورجینال' },
      { support: 'ارسال رایگان' },
    ],
    price: 260000,
    offPrice: 220000,
    discount: 15,
    image: 'https://s4.uupload.ir/files/item4_zr94.jpg',
  },
  {
    id: 5,
    name: 'بوت چلسی',
    description: [
      { support: 'گارانتی مادام العمر' },
      { support: 'اورجینال' },
      { support: 'ارسال رایگان' },
    ],
    price: 150000,
    offPrice: 150000,
    discount: 0,
    image: 'https://s4.uupload.ir/files/item5_24ye.jpg',
  },
  {
    id: 6,
    name: 'اسنیکرز آبی',
    description: [
      { support: 'گارانتی مادام العمر' },
      { support: 'اورجینال' },
      { support: 'ارسال رایگان' },
    ],
    price: 220000,
    offPrice: 200000,
    discount: 13,
    image: 'https://s4.uupload.ir/files/item6_7jfy.jpg',
  },
];
